name: Publish Edoc

on:
  push:
    branches: [ main ]

jobs:

  publish:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.2.4

    steps:
    - uses: actions/checkout@v2
    - name: Build docs
      run: rebar3 edoc
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
