name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    container:
      image: erlang:23.2.4-alpine

    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: apk add --update build-base linux-headers sudo
    - name: Compile
      run: rebar3 compile
    - name: Run property tests
      run: rebar3 proper || sudo `which rebar3` proper || sudo dmesg | grep -i lockdown
    - name: Run regression tests
      run: rebar3 proper --regressions
    - name: Build docs
      run: rebar3 edoc
    - name: Run tests
      run: rebar3 do eunit, ct
    - name: Run dialyzer
      run: rebar3 dialyzer
