name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run test on eBPF capable host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_REF
        script: |
          git clone --branch $GITHUB_REF https://github.com/oskardrums/ebpf
          cd ebpf
          rebar3 as test do compile, ct, proper, edoco, dialyzer
          cd ../
          rm -rf ebpf/
