name: Erlang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.2.4

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Build docs
      run: rebar3 edoc
    - name: Run tests
      run: sudo `which rebar3` do eunit, ct
    - name: Run property tests
      run: rebar3 proper
    - name: Run regression tests
      run: rebar3 proper --regressions
    - name: Run dialyzer
      run: rebar3 dialyzer
